# Site settings
title: 夏娃的时间 Time of Eve
url: "http://majiajin.github.io"
baseurl: ""
timezone: Asia/Beijing

# Personal information
author: Jordi Ma
avatar: "https://pic3.zhimg.com/v2-5008c81c55f65d5e634baa25e2f843b1_xl.jpg"
profile: 颜丑文良，醒梦如一

profile_links:
  微博: "https://www.weibo.com/jordima"
  知乎: "https://www.zhihu.com/people/jordima"

excerpt_separator: <!--more-->

header:
  links:
    商业研究: /business/
    学术研究: /academic/
    文档目录: /category/

permalink: /archivers/:title
plugins:
 - jekyll-seo-tag
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 8
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
